### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/goodwatch#10]
Because flashing a wrist-watch takes time, and because minor mistakes in power management can quickly murder our CR2016 battery, we will need an accurate simulator to test the firmware.  We can build this either on [msp430simu](https://github.com/travisgoodspeed/msp430simu/) (Python) or [mspsim](https://github.com/mspsim/mspsim) (Java).

In the short term, a bit of unit testing and maybe an LCD display simulator might be sufficient.  In the long term, we will want accurate models of the clocks and power management, with some mechanism for estimating power drain and comparing the power consumption of separate CPU branches.

Neighbor @cr has volunteered to tackle this issue.

**Comment by cr** [comment]
Yeah, probably for the better. I won't get around to contributing anything. Sorry for not being more vocal bout that.

**Comment by travisgoodspeed** [comment]
No worries, neighbor.
