### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by osresearch** [travisgoodspeed/goodwatch#109]
What is the license for the firmware source and Goodwatch schematics?

**Comment by travisgoodspeed** [comment]
The project under a beerware license, as found in `README.md`.

> In the rare case that you find this project to be useful, you owe me a pint of good, hoppy pale ale. All license to use this project is revoked if you try to pass off a pilsner instead.

Feel free to reuse whatever parts of the code and hardware you like for your excellent CharlieWatch project, but I will collect that pint the next time we're in the same town.
