### ISSUE TITLE
Programmer Jig

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/goodwatch#13]
While a watch development kit can be constructed with fly wires and an old GoodFET, it would be far classier to have a programmer jig that could sit beneath a GoodWatch board to program it or remain beneath it for integration testing or to act as a radio host.

Close this issue when we have such a jig, constructed to match the GoodWatch10's layout.  Friction and stiff wires should be used in lieu of pogo plugs, if possible.

**Comment by brainstorm** [comment]
Hi Travis, I used this one successfully in the past:

https://github.com/ebuller/openfixture

You just have to mark the pad placements in `Eco1.User` in KiCad, give the `.kicad_pcb` to a openfixture script and the magic of OpenSCAD scripting does the rest (DXF output ready to be laser-cut at your nearest hackerspace).

Handy documentation and assembly guide over here:

http://tinylabs.io/openfixture/

There are more lightweight fixtures out there, but not many parametrized/automated ones and so well suited for KiCad :)

**Comment by travisgoodspeed** [comment]
Closing this issue in favor of a pocket watch design that can serve double-duty as a programmer.

**Comment by sconklin** [comment]
I am absolutely up for this but . . . I can't commit to any sort of
schedule.

TL:DR is that we were planning to move out of state, but then decided to
stay, but as a consequence almost all my prototyping and fabrication
capabilities are still unavailable.

With any luck, I'll be getting back to normal in a few weeks, but it could
be March before I'm at anything close to full speed.

The openfixture link looks intriguing.

Steve

**Comment by travisgoodspeed** [comment]
No worries, Steve.  Just reopen this issue when you get your lab back together, and your design files for a jig will of course still be accepted to the repo.
