### ISSUE TITLE
Where to get started?

### ISSUE THREAD

**Issue by cintema** [travisgoodspeed/goodwatch#145]
Just came  across this project page, and I find it that amazing that I'm just about to buy a nice black casio ca506 (with inverted LCD) on ebay. I recognized that you're even working on DAPNET reception.
However, I couldn't figure out how to get the PCB for the Goodwatch30 (or even better Goodwatch31, for the proposed backlight support).
Will you produce a "mini-series" of PCBs allowing users (like me) to obtain one or two?
Thank you!

**Comment by travisgoodspeed** [comment]
GoodWatch31 hasn't been completed yet, I'm afraid.  There's an [open issue](https://github.com/travisgoodspeed/goodwatch/issues/121) to track its development, but it's stalled as I spend my time on other projects.

To get started, read the [Construction Guide](https://github.com/travisgoodspeed/goodwatch/wiki/ConstructionGuide) and send me your shipping address by email.  It is my first name at radiant machines dot com.  I'll toss four PCBs in an envelope and you can solder them at home with parts from the [GoodWatch30 BOM](https://github.com/travisgoodspeed/goodwatch/wiki/GoodWatch30) ordered from Digikey or Mouser.
