### ISSUE TITLE
Add beerware license

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [travisgoodspeed/goodwatch#167]
"In the rare case that you find this project to be useful, you owe me a pint of good, hoppy pale ale. All license to use this project is revoked if you try to pass off a pilsner instead."

Sounds like https://fedoraproject.org/wiki/Licensing/Beerware beerware license would be right up your valley!

**Comment by travisgoodspeed** [comment]
Much obliged, but I don't think I'll formalize the licensing.
