### ISSUE TITLE
Capacitor supply issues

### ISSUE THREAD

**Issue by qdot** [travisgoodspeed/goodwatch#42]
The following capacitors used in the 10 and 20 BOMs are both showing out of stock at digikey and mouser:

- CL10A476MQENRBE (Lead time: estimated 6 weeks at digikey)
- 02016D104KAT2A (Lead time: estimated 2 weeks at digikey)

Might want to find some equivalent parts if there's any plans to release this publicly before the end of the year.

**Comment by mossmann** [comment]
Is there a reason that the design uses 0201s instead of 0402s?

**Comment by travisgoodspeed** [comment]
On the back side, we don't quite have vertical room for 0402s.  On the front side, they should work wherever there is space to adjust the pads.

**Comment by skytee** [comment]
It looks like there is sufficient space on the front to put all resistors and capacitors, and make them 0402. What do you think?

**Comment by etbusch** [comment]
I replaced the following out-of-stock MuRata caps with TDK replacements:

C2, C3, C8, C9: C0603X6S0J104K030BC [Digi-Key](https://www.digikey.com/product-detail/en/tdk-corporation/C0603X6S0J104K030BC/445-8000-1-ND/2792136)

C6, C7: C0603C0G1E180J030BA [Digi-Key](https://www.digikey.com/product-detail/en/tdk-corporation/C0603C0G1E180J030BA/445-4657-1-ND/2050263)

**Comment by travisgoodspeed** [comment]
Closed this issue with updated BOM.txt for the GoodWatch21.  I'll look at larger cap sizes for the GW30.
