### ISSUE TITLE
Making Github Public

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/goodwatch#57]
Howdy y'all,

I'll be making the github project public this week, maybe even this evening.  Please don't be offended if I drop you from the collaborator's list as part of that process.

73 from Pizza Rat City,
--Travis

**Comment by fulligjimmy** [comment]
nagyon jó ez a goodwatch!

**Comment by travisgoodspeed** [comment]
Köszönöm szépen.
