### ISSUE TITLE
Castellated holes, workaround (low prior., manuf.)

### ISSUE THREAD

**Issue by luftek** [travisgoodspeed/goodwatch#59]
Hi, thank you for sharing this project.
Castellated holes:
- [x] some PCB manufacturers don't support castellated holes
- [x] usually some $ diff

Needs a simple change in Edge.Cuts
Similarly I did to pluto watch
https://github.com/carrotIndustries/pluto/issues/11

**Comment by travisgoodspeed** [comment]
Thank you kindly for the suggestion, but I think I'd rather keep the cuts in the Gerbers the same as the final release.  Gold Phoenix PCB supports the holes without complaint.
