### ISSUE TITLE
OOK Emulation Example

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/goodwatch#85]
Use this issue to track development of a quick emulator for these cheap OOK remote controls, including support for the full power table and safety checks to identify packet frame under/overflows.

![img_20180404_160728](https://user-images.githubusercontent.com/770671/38331871-821c831c-3822-11e8-8a64-15ffe9d7b45e.jpg)

**Comment by travisgoodspeed** [comment]
The OOK example is now fully functional.  I'll close this issue after documented it in the Wiki.

**Comment by travisgoodspeed** [comment]
Documentation is at https://github.com/travisgoodspeed/goodwatch/wiki/OOK_Example

I'll add a few screenshots, then close this issue.

**Comment by etbusch** [comment]
Awesome! I'm excited to dig into this, and to develop new applications once my LimeSDR mini comes in to replace a failed RTL-SDR. Thanks for keeping the momentum moving forward on this project!
